export const home = <i className="fa-solid fa-house"></i>;
export const list = <i className="fa-solid fa-list-check"></i>;
export const check = <i className="fa-solid fa-check"></i>;
export const todo = <i className="fa-solid fa-clipboard-list"></i>;
export const trash = <i className="fa-solid fa-trash"></i>;
export const edit = <i className="fa-solid fa-file-pen"></i>;
export const plusA = <i className="fa-solid fa-plus fa-beat-fade"></i>;
export const signout = <i className="fa-solid fa-right-from-bracket"></i>;
export const add = <i className="fa-solid fa-plus"></i>;
export const navbars = <i className="fa-solid fa-bars fa-beat"></i>;
export const plus = <i className="fa-solid fa-plus"></i>;
export const arrowLeft = <i className="fa-solid fa-arrow-left fa-beat"></i>;
