name: ProjectManagmentApp-Mern CI

on:
  push:
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'node'
  
    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run Jest Tests
      run: npm run test

    - name: Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          .next
          coverage
